# .streamlit/config.toml

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[logger]
level = "info"

[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#F3F4F6"
secondaryBackgroundColor = "#EFF6FF"
textColor = "#1E3A8A"
font = "sans serif"